package pt.piscina.ds.entities;
// Generated 17/nov/2018 23:41:51 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Acesso generated by hbm2java
 */
@Entity
@Table(name = "acesso", catalog = "gestgym", uniqueConstraints = @UniqueConstraint(columnNames = "cartao_acesso_id"))
public class Acesso implements java.io.Serializable {

	private Long id;
	private CartaoAcesso cartaoAcesso;
	private String data;

	public Acesso() {
	}

	public Acesso(CartaoAcesso cartaoAcesso, String data) {
		this.cartaoAcesso = cartaoAcesso;
		this.data = data;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cartao_acesso_id", unique = true, nullable = false)
	public CartaoAcesso getCartaoAcesso() {
		return this.cartaoAcesso;
	}

	public void setCartaoAcesso(CartaoAcesso cartaoAcesso) {
		this.cartaoAcesso = cartaoAcesso;
	}

	@Column(name = "data", nullable = false, length = 45)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

}
