package pt.piscina.ds.entities;
// Generated 17/nov/2018 20:51:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Antonimo generated by hbm2java
 */
@Entity
@Table(name = "antonimo", catalog = "gestgym")
public class Antonimo implements java.io.Serializable {

	private long id;
	private String descricao;
	private String descricaoInversa;

	public Antonimo() {
	}

	public Antonimo(long id) {
		this.id = id;
	}

	public Antonimo(long id, String descricao, String descricaoInversa) {
		this.id = id;
		this.descricao = descricao;
		this.descricaoInversa = descricaoInversa;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "descricao", length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "descricao_inversa", length = 45)
	public String getDescricaoInversa() {
		return this.descricaoInversa;
	}

	public void setDescricaoInversa(String descricaoInversa) {
		this.descricaoInversa = descricaoInversa;
	}

}
