package pt.piscina.ds.entities;
// Generated 17/nov/2018 20:51:16 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Atividade generated by hbm2java
 */
@Entity
@Table(name = "atividade", catalog = "gestgym", uniqueConstraints = @UniqueConstraint(columnNames = "descricao"))
public class Atividade implements java.io.Serializable {

	private Long id;
	private String descricao;
	private Set<Escalao> escalaos = new HashSet<Escalao>(0);

	public Atividade() {
	}

	public Atividade(String descricao) {
		this.descricao = descricao;
	}

	public Atividade(String descricao, Set<Escalao> escalaos) {
		this.descricao = descricao;
		this.escalaos = escalaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "descricao", unique = true, nullable = false, length = 20)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atividade")
	public Set<Escalao> getEscalaos() {
		return this.escalaos;
	}

	public void setEscalaos(Set<Escalao> escalaos) {
		this.escalaos = escalaos;
	}

}
