package pt.piscina.ds.entities;
// Generated 17/nov/2018 20:51:16 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AtividadeEpoca generated by hbm2java
 */
@Entity
@Table(name = "atividade_epoca", catalog = "gestgym", uniqueConstraints = @UniqueConstraint(columnNames = { "epoca_id",
		"nivel_id" }))
public class AtividadeEpoca implements java.io.Serializable {

	private Long id;
	private Epoca epoca;
	private Nivel nivel;
	private Set<Horario> horarios = new HashSet<Horario>(0);

	public AtividadeEpoca() {
	}

	public AtividadeEpoca(Epoca epoca, Nivel nivel) {
		this.epoca = epoca;
		this.nivel = nivel;
	}

	public AtividadeEpoca(Epoca epoca, Nivel nivel, Set<Horario> horarios) {
		this.epoca = epoca;
		this.nivel = nivel;
		this.horarios = horarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "epoca_id", nullable = false)
	public Epoca getEpoca() {
		return this.epoca;
	}

	public void setEpoca(Epoca epoca) {
		this.epoca = epoca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nivel_id", nullable = false)
	public Nivel getNivel() {
		return this.nivel;
	}

	public void setNivel(Nivel nivel) {
		this.nivel = nivel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "atividadeEpoca")
	public Set<Horario> getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set<Horario> horarios) {
		this.horarios = horarios;
	}

}
