package pt.piscina.ds.entities;
// Generated 17/nov/2018 23:41:51 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CartaoAcesso generated by hbm2java
 */
@Entity
@Table(name = "cartao_acesso", catalog = "gestgym", uniqueConstraints = @UniqueConstraint(columnNames = "numero"))
public class CartaoAcesso implements java.io.Serializable {

	private Long id;
	private Pessoa pessoa;
	private String numero;
	private Set<Acesso> acessos = new HashSet<Acesso>(0);

	public CartaoAcesso() {
	}

	public CartaoAcesso(Pessoa pessoa, String numero) {
		this.pessoa = pessoa;
		this.numero = numero;
	}

	public CartaoAcesso(Pessoa pessoa, String numero, Set<Acesso> acessos) {
		this.pessoa = pessoa;
		this.numero = numero;
		this.acessos = acessos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pessoa_id", nullable = false)
	public Pessoa getPessoa() {
		return this.pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	@Column(name = "numero", unique = true, nullable = false, length = 45)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "cartaoAcesso")
	public Set<Acesso> getAcessos() {
		return this.acessos;
	}

	public void setAcessos(Set<Acesso> acessos) {
		this.acessos = acessos;
	}

}
