package pt.piscina.ds.entities;
// Generated 17/nov/2018 20:51:16 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DadosCc generated by hbm2java
 */
@Entity
@Table(name = "dados_cc", catalog = "gestgym")
public class DadosCc implements java.io.Serializable {

	private int id;

	public DadosCc() {
	}

	public DadosCc(int id) {
		this.id = id;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
