package pt.piscina.ds.entities;
// Generated 17/nov/2018 20:51:16 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Divisao generated by hbm2java
 */
@Entity
@Table(name = "divisao", catalog = "gestgym")
public class Divisao implements java.io.Serializable {

	private Long id;
	private Espaco espaco;
	private String descricao;
	private Set<Horario> horarios = new HashSet<Horario>(0);

	public Divisao() {
	}

	public Divisao(Espaco espaco, String descricao) {
		this.espaco = espaco;
		this.descricao = descricao;
	}

	public Divisao(Espaco espaco, String descricao, Set<Horario> horarios) {
		this.espaco = espaco;
		this.descricao = descricao;
		this.horarios = horarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "espaco_id", nullable = false)
	public Espaco getEspaco() {
		return this.espaco;
	}

	public void setEspaco(Espaco espaco) {
		this.espaco = espaco;
	}

	@Column(name = "descricao", nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "divisao")
	public Set<Horario> getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set<Horario> horarios) {
		this.horarios = horarios;
	}

}
