package pt.piscina.ds.entities;
// Generated 17/nov/2018 23:41:51 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Instalacao generated by hbm2java
 */
@Entity
@Table(name = "instalacao", catalog = "gestgym")
public class Instalacao implements java.io.Serializable {

	private Long id;
	private String descricao;
	private String rua;
	private String ruaComplemento;
	private String codPostal;
	private String localidade;
	private Set<Espaco> espacos = new HashSet<Espaco>(0);

	public Instalacao() {
	}

	public Instalacao(String descricao, String rua, String codPostal, String localidade) {
		this.descricao = descricao;
		this.rua = rua;
		this.codPostal = codPostal;
		this.localidade = localidade;
	}

	public Instalacao(String descricao, String rua, String ruaComplemento, String codPostal, String localidade,
			Set<Espaco> espacos) {
		this.descricao = descricao;
		this.rua = rua;
		this.ruaComplemento = ruaComplemento;
		this.codPostal = codPostal;
		this.localidade = localidade;
		this.espacos = espacos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "descricao", nullable = false, length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "rua", nullable = false, length = 200)
	public String getRua() {
		return this.rua;
	}

	public void setRua(String rua) {
		this.rua = rua;
	}

	@Column(name = "rua_complemento", length = 50)
	public String getRuaComplemento() {
		return this.ruaComplemento;
	}

	public void setRuaComplemento(String ruaComplemento) {
		this.ruaComplemento = ruaComplemento;
	}

	@Column(name = "cod_postal", nullable = false, length = 8)
	public String getCodPostal() {
		return this.codPostal;
	}

	public void setCodPostal(String codPostal) {
		this.codPostal = codPostal;
	}

	@Column(name = "localidade", nullable = false, length = 50)
	public String getLocalidade() {
		return this.localidade;
	}

	public void setLocalidade(String localidade) {
		this.localidade = localidade;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "instalacao")
	public Set<Espaco> getEspacos() {
		return this.espacos;
	}

	public void setEspacos(Set<Espaco> espacos) {
		this.espacos = espacos;
	}

}
