package pt.piscina.ds.entities;
// Generated 17/nov/2018 20:51:16 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nivel generated by hbm2java
 */
@Entity
@Table(name = "nivel", catalog = "gestgym")
public class Nivel implements java.io.Serializable {

	private Long id;
	private Escalao escalao;
	private int NOrdem;
	private String descricao;
	private Set<AtividadeEpoca> atividadeEpocas = new HashSet<AtividadeEpoca>(0);

	public Nivel() {
	}

	public Nivel(Escalao escalao, int NOrdem, String descricao) {
		this.escalao = escalao;
		this.NOrdem = NOrdem;
		this.descricao = descricao;
	}

	public Nivel(Escalao escalao, int NOrdem, String descricao, Set<AtividadeEpoca> atividadeEpocas) {
		this.escalao = escalao;
		this.NOrdem = NOrdem;
		this.descricao = descricao;
		this.atividadeEpocas = atividadeEpocas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "escalao_id", nullable = false)
	public Escalao getEscalao() {
		return this.escalao;
	}

	public void setEscalao(Escalao escalao) {
		this.escalao = escalao;
	}

	@Column(name = "n_ordem", nullable = false)
	public int getNOrdem() {
		return this.NOrdem;
	}

	public void setNOrdem(int NOrdem) {
		this.NOrdem = NOrdem;
	}

	@Column(name = "descricao", nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivel")
	public Set<AtividadeEpoca> getAtividadeEpocas() {
		return this.atividadeEpocas;
	}

	public void setAtividadeEpocas(Set<AtividadeEpoca> atividadeEpocas) {
		this.atividadeEpocas = atividadeEpocas;
	}

}
