package pt.piscina.ds.entities;
// Generated 17/nov/2018 23:41:51 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Periodo generated by hbm2java
 */
@Entity
@Table(name = "periodo", catalog = "gestgym", uniqueConstraints = @UniqueConstraint(columnNames = "descricao"))
public class Periodo implements java.io.Serializable {

	private Long id;
	private Periodicidade periodicidade;
	private String descricao;
	private Set<Horario> horarios = new HashSet<Horario>(0);

	public Periodo() {
	}

	public Periodo(Periodicidade periodicidade, String descricao) {
		this.periodicidade = periodicidade;
		this.descricao = descricao;
	}

	public Periodo(Periodicidade periodicidade, String descricao, Set<Horario> horarios) {
		this.periodicidade = periodicidade;
		this.descricao = descricao;
		this.horarios = horarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "periodicidade_id", nullable = false)
	public Periodicidade getPeriodicidade() {
		return this.periodicidade;
	}

	public void setPeriodicidade(Periodicidade periodicidade) {
		this.periodicidade = periodicidade;
	}

	@Column(name = "descricao", unique = true, nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodo")
	public Set<Horario> getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set<Horario> horarios) {
		this.horarios = horarios;
	}

}
