package pt.piscina.ds.entities;
// Generated 17/nov/2018 20:51:16 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Periodicidade generated by hbm2java
 */
@Entity
@Table(name = "periodicidade", catalog = "gestgym", uniqueConstraints = @UniqueConstraint(columnNames = "descricao"))
public class Periodicidade implements java.io.Serializable {

	private Long id;
	private String descricao;
	private Set<Periodo> periodos = new HashSet<Periodo>(0);

	public Periodicidade() {
	}

	public Periodicidade(String descricao) {
		this.descricao = descricao;
	}

	public Periodicidade(String descricao, Set<Periodo> periodos) {
		this.descricao = descricao;
		this.periodos = periodos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "descricao", unique = true, nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "periodicidade")
	public Set<Periodo> getPeriodos() {
		return this.periodos;
	}

	public void setPeriodos(Set<Periodo> periodos) {
		this.periodos = periodos;
	}

}
