package pt.piscina.ds.entities;
// Generated 17/nov/2018 20:51:16 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoUtente generated by hbm2java
 */
@Entity
@Table(name = "tipo_utente", catalog = "gestgym")
public class TipoUtente implements java.io.Serializable {

	private Long id;
	private int NOrdem;
	private String descricao;
	private float descontoPercentagem;
	private float descontoValor;
	private Set<Utente> utentes = new HashSet<Utente>(0);

	public TipoUtente() {
	}

	public TipoUtente(int NOrdem, String descricao, float descontoPercentagem, float descontoValor) {
		this.NOrdem = NOrdem;
		this.descricao = descricao;
		this.descontoPercentagem = descontoPercentagem;
		this.descontoValor = descontoValor;
	}

	public TipoUtente(int NOrdem, String descricao, float descontoPercentagem, float descontoValor, Set<Utente> utentes) {
		this.NOrdem = NOrdem;
		this.descricao = descricao;
		this.descontoPercentagem = descontoPercentagem;
		this.descontoValor = descontoValor;
		this.utentes = utentes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "n_ordem", nullable = false)
	public int getNOrdem() {
		return this.NOrdem;
	}

	public void setNOrdem(int NOrdem) {
		this.NOrdem = NOrdem;
	}

	@Column(name = "descricao", nullable = false, length = 45)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Column(name = "desconto_percentagem", nullable = false, precision = 10, scale = 0)
	public float getDescontoPercentagem() {
		return this.descontoPercentagem;
	}

	public void setDescontoPercentagem(float descontoPercentagem) {
		this.descontoPercentagem = descontoPercentagem;
	}

	@Column(name = "desconto_valor", nullable = false, precision = 10, scale = 0)
	public float getDescontoValor() {
		return this.descontoValor;
	}

	public void setDescontoValor(float descontoValor) {
		this.descontoValor = descontoValor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoUtente")
	public Set<Utente> getUtentes() {
		return this.utentes;
	}

	public void setUtentes(Set<Utente> utentes) {
		this.utentes = utentes;
	}

}
