package pt.piscina.ds.entities;
// Generated 17/nov/2018 23:41:51 by Hibernate Tools 5.2.3.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TipoContacto generated by hbm2java
 */
@Entity
@Table(name = "tipo_contacto", catalog = "gestgym", uniqueConstraints = @UniqueConstraint(columnNames = "descricao"))
public class TipoContacto implements java.io.Serializable {

	private Long id;
	private int NOrdem;
	private String descricao;
	private Set<Contacto> contactos = new HashSet<Contacto>(0);

	public TipoContacto() {
	}

	public TipoContacto(int NOrdem, String descricao) {
		this.NOrdem = NOrdem;
		this.descricao = descricao;
	}

	public TipoContacto(int NOrdem, String descricao, Set<Contacto> contactos) {
		this.NOrdem = NOrdem;
		this.descricao = descricao;
		this.contactos = contactos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "n_ordem", nullable = false)
	public int getNOrdem() {
		return this.NOrdem;
	}

	public void setNOrdem(int NOrdem) {
		this.NOrdem = NOrdem;
	}

	@Column(name = "descricao", unique = true, nullable = false, length = 20)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContacto")
	public Set<Contacto> getContactos() {
		return this.contactos;
	}

	public void setContactos(Set<Contacto> contactos) {
		this.contactos = contactos;
	}

}
