package pt.uc.dei.itf.errors;

public enum ErrorMessage {
	//GENERAL
	END_DATE_MUST_BE_AFTER_BEGIN_DATE,
	FATAL_ERROR, //AKA "S**t happens" ---> Lets pray for !(S**t happens)
	UNIQUE_NAME_ALREADY_EXISTS,
	NULL_OR_EMPTY_FIELDS,
	MUST_BE_POSITIVE_VALUE,
	MUST_BE_NON_NEGATIVE_VALUE,
	MUST_BE_DIRECTOR_OR_PROJECT_MANAGER,
	INVALID_PERCENTAGE_ALLOCATION,
	DATE_MUST_NOT_BE_PAST,
	INVALID_FIELDS,
	
	//TASK update DETAILS
	TASK_CANNOT_START_BEFORE_PROJECT, //to update task begin date
	TASK_ALREADY_IN_PROGRESS, //to update task begin date
	TASK_CANNOT_END_AFTER_PROJECT, //to update task end date
	TASK_MUST_END_AFTER_ALL_PRECEDENTS_START,
	TASK_MUST_BEGIN_BEFORE_ALL_NEXT_END,
	TASK_HAS_ALLOCATIONS_OUTSIDE_DATE_INTERVAL,
	
	//TASK create
	TASK_CREATE_USER_NOT_ALLOWED,
	TASK_MUST_HAVE_POSIVE_DURATION,
	TASK_MUST_START_TOMORROW_OR_AFTER,
	
	//USER create or update
	USER_MUST_HAVE_A_ROLE,
	USER_VISITOR_MUST_HAVE_A_SINGLE_ROLE,
	EMAIL_ALREADY_EXISTS,
	ROLE_DOES_NOT_PERMIT_OPERATION,
	USER_HAS_MANAGED_PROJECTS_SO_MUST_BE_USER_OR_DIRECTOR,
	
	//CREATE or update Holiday
	DATE_IS_ALREADY_AN_HOLIDAY,
	HOLIDAY_DATE_MUST_BE_FUTURE,
	
	//create taskwork - register hours in task
	WORKED_HOURS_EXCEEDS_MAX_ALLOWED,
	
	INVALID_PRECEDENCE,
	
	//update allocation dates
	ALLOCATION_CANNOT_BE_OUTSIDE_TASK_DATES,
	
	//Login
	USER_NOT_ACTIVE,
	LOGIN_FAILED,
	
	//get workers to task - for date interval given by user
	TASK_OUTSIDE_DATES,
	ALLOCATIONS_ALREADY_IN_INTERVAL,
	DATE_MUST_BE_FUTURE,
	
	//remove allocation
	USER_HAS_WORKING_HOURS_IN_ALLOCATION,
	
	//update allocation dates
	CAN_NOT_CHANGE_ENDING_ALLOCATIONS,
	CAN_NOT_CHANGE_BEGIN_DATE_IN_DECURRING_ALLOCATIONS,
	USER_HAS_NOT_REQUIRED_PERCENTAGE_ALLOCATION_FOR_PERIOD,
	
	//Project update or create
	PROJECT_HAS_TASKS_OUTSIDE_DATES,
	CANNOT_CHANGE_MANAGER_ON_LAST_PROJECT_DAY,
	PROJECT_ID_ALREADY_EXISTS,
	
	//For bridges when they try to connect to DataServer via REST
	DATASERVER_OFFLINE,
	
	CLIENT_NAME_EXISTS,
	CAN_ONLY_REMOVE_ALLOCATIONS_ENDING_IN_FUTURE,
}
